<font color=Green>
    
# **2.7 Agregar y quitar valores a un array**

</font>

In [1]:
#arange se usa como los scling el (a,b,c) el a paso inicial b paso final y c la secuncia
import numpy as np

arr = np.arange(0,20,2)
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [2]:
#funcion random.rand genera num aleatorios como forma (4,3) 4 filas y 3 columnas
arr_flot = np.random.rand(4,3)
arr_flot

array([[0.27789226, 0.91702095, 0.21767685],
       [0.81827213, 0.19291708, 0.9992221 ],
       [0.24531007, 0.89790323, 0.62246428],
       [0.81329951, 0.86757574, 0.09462726]])

In [3]:
#randint genera num os enteros  (a,b) a genera filas y b genear columnas
arr_ent = np.random.randint(100, size=(2,3))
arr_ent

array([[20, 13, 78],
       [56, 64, 73]])

In [4]:
#full genera  atrix 3 *3 y voleres de el mismo para todos
arr_6 = np.full((3,3),6)
arr_6

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [5]:
#funciones añadir elementos al arreglo
np.append(arr, [12,13,14,51])

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 12, 13, 14, 51])

In [6]:
#agrega en una posion determinada arr, el indice 2 los dos numeros 42,34
np.insert(arr,2, [42,34])

array([ 0,  2, 42, 34,  4,  6,  8, 10, 12, 14, 16, 18])

In [7]:
np.insert(arr_6,2, [1,2,4])

array([6, 6, 1, 2, 4, 6, 6, 6, 6, 6, 6, 6])

In [10]:
arr_ent

array([[20, 13, 78],
       [56, 64, 73]])

In [8]:
#funcion elimenar la posion y el eje si es de filas o columnas
# axis=1 elimina la columna (en este caso la 0(20,56))
np.delete(arr_ent,0,axis=1)

array([[13, 78],
       [64, 73]])

In [11]:
#axis=0 elimiina la fila(en este caso la 0(56,64,73))
np.delete(arr_ent,0,axis=0)

array([[56, 64, 73]])