<font color=Green>
    
# **2.8 Transformaciones**

</font>


## <font color=#003d5c>_As Type_ </font>

### Este método nos permite modificar el tipo de dato de los valores de un `array`

In [1]:
import numpy as np

arr_ent = np.random.randint(100, size=(3,4))
arr_ent

array([[34, 22, 65, 87],
       [96, 77,  1, 19],
       [71, 41, 99, 90]])

In [2]:
#convierte el tipo de dato en este caso de int a float
arr_ent.astype(float)

array([[34., 22., 65., 87.],
       [96., 77.,  1., 19.],
       [71., 41., 99., 90.]])

## <font color=#003d5c>_Sort_ </font>

### Este método nos permite ordenar los valores de un `array`

In [3]:
arr_ent

array([[34, 22, 65, 87],
       [96, 77,  1, 19],
       [71, 41, 99, 90]])

In [4]:
#ordenar fila por fila
arr_ent.sort()
arr_ent

array([[35, 67, 67, 76],
       [ 1, 24, 84, 86],
       [ 9, 16, 20, 62]])

In [4]:
#ordena por columnas con axis = 0
arr_ent.sort(axis=0)
arr_ent

array([[34, 22,  1, 19],
       [71, 41, 65, 87],
       [96, 77, 99, 90]])

## <font color=#003d5c>_Reshape_ </font>

### Este método nos permite modificar las dimensiones de un `array`.

In [5]:
arr_ent

array([[34, 22,  1, 19],
       [71, 41, 65, 87],
       [96, 77, 99, 90]])

In [6]:
#reshape reforar el mismo arreglo
arr_ent = arr_ent.reshape(4,3)
arr_ent

array([[34, 22,  1],
       [19, 71, 41],
       [65, 87, 96],
       [77, 99, 90]])

## <font color=#003d5c>_Flatten_ </font>

### Este método crea un array unidimensional desde el original.

In [7]:
#flatten aplanar  el arreglo
plano_arr = arr_ent.flatten()

print(arr_ent)
#ahora se aplica flatten
print(plano_arr)

[[34 22  1]
 [19 71 41]
 [65 87 96]
 [77 99 90]]
[34 22  1 19 71 41 65 87 96 77 99 90]


## <font color=#003d5c>_To List_ </font>

### Este método crea una lista a partir de un array

In [9]:
#convertir a lista
lista_arr = plano_arr.tolist()
lista_arr


[34, 22, 1, 19, 71, 41, 65, 87, 96, 77, 99, 90]

In [10]:
type(lista_arr)

list

## <font color=#003d5c>_Separar y juntar arrays_ </font>

In [11]:
#separar con split lleva dos argumentos 1 el arreglo y 2 las partes a separar
arrays= np.split(arr_ent,4)
arrays

[array([[34, 22,  1]]),
 array([[19, 71, 41]]),
 array([[65, 87, 96]]),
 array([[77, 99, 90]])]

In [12]:
#concadenar  axis=1 filas horizaontal  axis=0 columnas vertical
np.concatenate((arrays[1],arrays[0]),axis=1)

array([[19, 71, 41, 34, 22,  1]])

## <font color=#003d5c>_La matriz transpuesta_ </font>

In [13]:
arr_ent

array([[34, 22,  1],
       [19, 71, 41],
       [65, 87, 96],
       [77, 99, 90]])

In [14]:
#coloca la fila como columna y la columna como fila
t_arr = arr_ent.T
t_arr

array([[34, 19, 65, 77],
       [22, 71, 87, 99],
       [ 1, 41, 96, 90]])